htmdecoder: Fix compile issue with older GCC
In this commit:
  ee18396a59e6 htmdecoder: Use standard endian convertion function

We introduced a compile issue with GCC 5:
    htm/htm.c: In function 'htm_decode_fetch':
    htm/htm.c:142:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
      t.value = be64toh( *(uint64_t *)bytes );

This fixes it without losing the performance benefits of the original
patch.

Signed-off-by: Michael Neuling <mikey@neuling.org>